"""Cards creted and updated

Revision ID: 04b2ef7df69b
Revises: 2392338d79d0
Create Date: 2022-09-28 00:56:54.116646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b2ef7df69b'
down_revision = '2392338d79d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('card', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'updated_at')
    op.drop_column('card', 'created_at')
    # ### end Alembic commands ###
