"""Auth Token

Revision ID: 2392338d79d0
Revises: 6fb2120835e8
Create Date: 2022-09-16 04:22:12.616313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2392338d79d0'
down_revision = '6fb2120835e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_token')
    # ### end Alembic commands ###
