"""Created and Updated

Revision ID: a40de13ccfc5
Revises: 04b2ef7df69b
Create Date: 2022-09-28 01:03:09.066844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40de13ccfc5'
down_revision = '04b2ef7df69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'updated_at')
    op.add_column('list', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('list', 'created_at')
    op.add_column('card', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
