"""Created and Updated

Revision ID: c3d1430e1e51
Revises: c1e4c5d7f8cf
Create Date: 2022-09-28 20:06:13.144053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d1430e1e51'
down_revision = 'c1e4c5d7f8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('list', 'updated_at')
    # ### end Alembic commands ###
